---
title: "expression_processing"
author: "Chandler Sutherland"
date: "2023-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggsignif)
library(ggpubr)
library(ggbeeswarm)
```


```{r}
nlr_only <- read.csv('/global/scratch/users/chandlersutherland/e16/cs_reports/rna_tip_tpm_nlr_only.tsv', sep='\t')
unmappable <- c('Zm00039ab351270', 'Zm00026ab135540', 'Zm00036ab418650',
                'Zm00001eb091500', 'Zm00001eb164880', 'Zm00001eb343890',
                'Zm00001eb391100', 'Zm00001eb405870', 'Zm00001eb405900',
                'Zm00001eb405930', 'Zm00033ab429000', 'Zm00029ab367660')

#remove the NLRs found to be unmappable by simulation 
nlr_only <- nlr_only %>% filter(!name %in% unmappable)
nlr_only<-nlr_only[-c(2)]
```

```{r}
b97_test <- nlr_only %>% filter(accession=='B97')%>% group_by(accession, name, HV) %>% 
  summarise(log2.TPM=mean(log2.TPM.),
            .groups = 'drop')

compare_means(log2.TPM~HV, b97_test, method = 'wilcox.test', paired = FALSE)
b97_test$HV <- factor(b97_test$HV, levels=c(0, 1))
ggplot(b97_test,
       aes(x=HV, y=log2.TPM, fill=HV))+
    geom_violin(lwd=0.25)+
  geom_quasirandom(alpha=0.3, size=0.5)+
   ylim(0,8.8)+
   geom_signif(comparisons=list(0, 1), 
               map_signif_level = TRUE, y_position = c(8, 7), test=wilcox.test, textsize=2, size=0.25)+
    scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  theme_classic()+
    theme(legend.position='none', text=element_text(size=10), 
          axis.title=element_blank()) +
  scale_x_discrete(labels=c('non-hv', 'hv'))
```

```{r}
summary <- nlr_only %>% group_by(accession, name, HV) %>% 
  summarise(log2.TPM=mean(log2.TPM.),
            .groups = 'drop')

compare_means(log2.TPM~HV, summary, method = 'wilcox.test', paired = FALSE)

samples <- summary$accession %>% unique()
p_calc <- function(sample, summary){
  x <- summary %>% filter(accession == sample)
  p <- compare_means(log2.TPM~HV, x, method = 'wilcox.test', paired = FALSE)$p
  return(p)
}
p_calc('B73', summary)
p_df <- data.frame(matrix(ncol=2,nrow=0))
colnames(p_df)<-c('accession', 'wilcoxon_p')


for (i in 1:length(samples)){
  p <- p_calc(samples[i],summary)
  p_df[nrow(p_df)+1,]<-c(samples[i],p)
}

p_df$wilcoxon_p <- p_df$wilcoxon_p %>% as.numeric()
p_df <- p_df[order(p_df$wilcoxon_p),]
p_df$sig <- p_df$wilcoxon_p < 0.05

p_ordered <- p_df$accession
p_df$accession <- factor(p_df$accession, levels=p_ordered)

ggplot(p_df, 
       aes(x=accession,y=wilcoxon_p))+
  geom_bar(stat='identity')+
  geom_hline(yintercept=0.05, color="red")
```
```{r,fig.width=12,fig.height=2}
nlr_only$HV <- factor(nlr_only$HV, levels=c(0, 1))
nlr_only$accession <- factor(nlr_only$accession, levels=p_ordered)
ggplot(nlr_only,
       aes(x=accession, y=log2.TPM., fill=HV))+
    geom_violin(lwd=0.25, position=position_dodge(0.7), adjust=2)+
  #geom_quasirandom(alpha=0.3, size=0.5)+
   ylim(0,8.8)+
    scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  theme_classic()+
    theme(legend.position='right', text=element_text(size=10), 
          axis.title=element_blank())
```

```{r,fig.width=18,fig.height=12}
b97_test <- nlr_only %>% filter(accession=='B97')%>% group_by(accession, name, HV) %>% 
  summarise(log2.TPM=mean(log2.TPM.),
            .groups = 'drop')

compare_means(log2.TPM~HV, b97_test, method = 'wilcox.test', paired = FALSE)
b97_test$HV <- factor(b97_test$HV, levels=c(0, 1))
summary$HV <- factor(summary$HV, levels=c(0, 1))

ggplot(summary,
       aes(x=HV, y=log2.TPM, fill=HV))+
    geom_violin(lwd=0.25)+
 #  ylim(0,8.8)+
  theme_classic()+
    geom_quasirandom(alpha=0.3, size=0.5)+
    theme(legend.position='none', text=element_text(size=20), 
          axis.title=element_blank()) +
  scale_x_discrete(labels=c('non-hv', 'hv'))+
  scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  facet_wrap(vars(accession), ncol=5)
```
```{r}
summary %>% group_by(HV) %>% count()
```


```{r}
compare_means(log2.TPM~HV, summary, method='wilcox.test', paired=FALSE)
summary$HV <- as.factor(summary$HV)
ggplot(summary,
       aes(x=HV, y=log2.TPM, fill=HV))+
    geom_violin(lwd=0.25, width=1.2)+
  geom_boxplot(width=0.1, color='darkgrey', alpha=0.2)+
 #  ylim(0,8.8)+
  theme_classic()+
 # geom_quasirandom(alpha=0.3, size=0.5)+
    theme(legend.position='none', text=element_text(size=20)) +
  scale_x_discrete(labels=c('non-hv', 'hv'))+
  scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  ylab('log2(TPM)')+xlab('')
```

```{r}
B73 <- summary %>% filter(accession=='B73')
compare_means(log2.TPM~HV, B73, method='wilcox.test', paired=FALSE)
B73$HV <- as.factor(B73$HV)
ggplot(B73,
       aes(x=HV, y=log2.TPM, fill=HV))+
    geom_violin(lwd=0.25, width=1.2)+
  geom_boxplot(width=0.1, color='darkgrey', alpha=0.2)+
 #  ylim(0,8.8)+
  theme_classic()+
 # geom_quasirandom(alpha=0.3, size=0.5)+
    theme(legend.position='none', text=element_text(size=20)) +
  scale_x_discrete(labels=c('non-hv', 'hv'))+
  scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  ylab('log2(TPM)')+xlab('')
```

